# Generated by Django 5.2.1 on 2025-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='naver_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
