# Generated by Django 5.2.4 on 2025-07-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topkeyword",
            old_name="search",
            new_name="search_history",
        ),
    ]
